language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t  pdimitri/docker-k8s-examples  -f Dockerfile.dev .

script: 
  - docker run -e CI=true pdimitri/docker-k8s-examples npm run test
  